//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendMusica.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBLossSoundsEntities : DbContext
    {
        public DBLossSoundsEntities()
            : base("name=DBLossSoundsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tb_Album> Tb_Album { get; set; }
        public virtual DbSet<Tb_Artista> Tb_Artista { get; set; }
        public virtual DbSet<Tb_Cancion> Tb_Cancion { get; set; }
        public virtual DbSet<Tb_CancionContents> Tb_CancionContents { get; set; }
        public virtual DbSet<Tb_LikeMusic> Tb_LikeMusic { get; set; }
        public virtual DbSet<Tb_Playlist> Tb_Playlist { get; set; }
        public virtual DbSet<Tb_PlaylistPrivacidad> Tb_PlaylistPrivacidad { get; set; }
        public virtual DbSet<Tb_Rol> Tb_Rol { get; set; }
        public virtual DbSet<Tb_Seguidos> Tb_Seguidos { get; set; }
        public virtual DbSet<Tb_TypesLikes> Tb_TypesLikes { get; set; }
        public virtual DbSet<Tb_Usuario> Tb_Usuario { get; set; }
    
        public virtual int sp_registerUser(string user, string email, string password, Nullable<int> iD_Rol, ObjectParameter registrado, ObjectParameter mensaje)
        {
            var userParameter = user != null ?
                new ObjectParameter("User", user) :
                new ObjectParameter("User", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var iD_RolParameter = iD_Rol.HasValue ?
                new ObjectParameter("ID_Rol", iD_Rol) :
                new ObjectParameter("ID_Rol", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_registerUser", userParameter, emailParameter, passwordParameter, iD_RolParameter, registrado, mensaje);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_ValidarUsuario(ObjectParameter loggeado, string user, string password)
        {
            var userParameter = user != null ?
                new ObjectParameter("User", user) :
                new ObjectParameter("User", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_ValidarUsuario", loggeado, userParameter, passwordParameter);
        }
    }
}
