//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendMusica.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BD_LOSS_SOUNDSEntities : DbContext
    {
        public BD_LOSS_SOUNDSEntities()
            : base("name=BD_LOSS_SOUNDSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ExceptionLog> ExceptionLog { get; set; }
        public virtual DbSet<tb_Album> tb_Album { get; set; }
        public virtual DbSet<tb_Artista> tb_Artista { get; set; }
        public virtual DbSet<tb_Cancion> tb_Cancion { get; set; }
        public virtual DbSet<tb_Comentarios> tb_Comentarios { get; set; }
        public virtual DbSet<tb_DisLikeMusic> tb_DisLikeMusic { get; set; }
        public virtual DbSet<tb_LikeMusic> tb_LikeMusic { get; set; }
        public virtual DbSet<tb_Playlist> tb_Playlist { get; set; }
        public virtual DbSet<tb_RolesPrivacidad> tb_RolesPrivacidad { get; set; }
        public virtual DbSet<tb_Seguidos> tb_Seguidos { get; set; }
        public virtual DbSet<tb_Usuario> tb_Usuario { get; set; }
    
        public virtual int sp_registerUser(string user, string password, Nullable<int> iD_Rol, ObjectParameter registrado, ObjectParameter mensaje)
        {
            var userParameter = user != null ?
                new ObjectParameter("User", user) :
                new ObjectParameter("User", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var iD_RolParameter = iD_Rol.HasValue ?
                new ObjectParameter("ID_Rol", iD_Rol) :
                new ObjectParameter("ID_Rol", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_registerUser", userParameter, passwordParameter, iD_RolParameter, registrado, mensaje);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_ValidarUsuario(ObjectParameter loggeado, string user, string password)
        {
            var userParameter = user != null ?
                new ObjectParameter("User", user) :
                new ObjectParameter("User", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_ValidarUsuario", loggeado, userParameter, passwordParameter);
        }
    }
}
