//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendMusica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Cancion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Cancion()
        {
            this.Tb_LikeMusic = new HashSet<Tb_LikeMusic>();
            this.Tb_Playlist = new HashSet<Tb_Playlist>();
        }
    
        public long ID_Cancion { get; set; }
        public long ID_Artista { get; set; }
        public long ID_Album { get; set; }
        public string Nombre_Cancion { get; set; }
        public Nullable<decimal> Numero_Cancion { get; set; }
        public string Ruta_Audio { get; set; }
        public byte[] Caratula_Cancion { get; set; }
        public int Duracion_Cancion { get; set; }
        public bool Activo { get; set; }
    
        public virtual Tb_Album Tb_Album { get; set; }
        public virtual Tb_Artista Tb_Artista { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual Tb_CancionContents Tb_CancionContents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_LikeMusic> Tb_LikeMusic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Playlist> Tb_Playlist { get; set; }
    }
}
