//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendMusica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Playlist
    {
        public int ID_Playlist { get; set; }
        public int ID_Usuario { get; set; }
        public long ID_Cancion { get; set; }
        public string Nombre_Playlist { get; set; }
        public Nullable<System.DateTime> Fecha_Creacion { get; set; }
        public Nullable<int> ID_PlayListPrivacidad { get; set; }
    
        public virtual Tb_Cancion Tb_Cancion { get; set; }
        public virtual Tb_PlaylistPrivacidad Tb_PlaylistPrivacidad { get; set; }
        public virtual Tb_Usuario Tb_Usuario { get; set; }
    }
}
