//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendMusica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Seguidos
    {
        public int ID_Seguidos { get; set; }
        public int ID_Usuario { get; set; }
        public long ID_Artista { get; set; }
    
        public virtual Tb_Artista Tb_Artista { get; set; }
        public virtual Tb_Usuario Tb_Usuario { get; set; }
    }
}
