//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendMusica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Usuario()
        {
            this.tb_Comentarios = new HashSet<tb_Comentarios>();
            this.tb_DisLikeMusic = new HashSet<tb_DisLikeMusic>();
            this.tb_LikeMusic = new HashSet<tb_LikeMusic>();
            this.tb_Playlist = new HashSet<tb_Playlist>();
            this.tb_Seguidos = new HashSet<tb_Seguidos>();
        }
    
        public int ID_USUARIO { get; set; }
        public string Nombre_Usuario { get; set; }
        public string Contrasena { get; set; }
        public Nullable<int> ID_Rol { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Comentarios> tb_Comentarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_DisLikeMusic> tb_DisLikeMusic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_LikeMusic> tb_LikeMusic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Playlist> tb_Playlist { get; set; }
        public virtual tb_RolesPrivacidad tb_RolesPrivacidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Seguidos> tb_Seguidos { get; set; }
    }
}
